language: python

dist: xenial

branches:
    only:
        - master
        - /\d+\.\d+\.x/
        - /\d+\.\d+(\.\d+)?/

python:
  - 3.6
  - 3.7
  - 3.8
  - nightly
  - pypy3

# command to install dependencies
install:
  - cd python3
  - pip install .
# - pip install -r requirements.txt

# command to run tests
script:
  - pytest

